"""Generate Terraform from a PolicyGate evidence packet.

This module only produces configuration text. It never runs Terraform and never
contacts AWS. The exact saved ``tfplan`` produced later is hashed and bound into
the approval document before a human signs it.

Credential handling is intentionally delegated to Amazon RDS. The generated
configuration enables ``manage_master_user_password`` so RDS creates and manages
the master credential in AWS Secrets Manager. PolicyGate does not generate, log,
or persist the database password.

Terraform state can still contain infrastructure-sensitive metadata and must be
treated as sensitive. The repository ignores local state/plan directories; a
production deployment should use an encrypted, access-controlled remote backend.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

_ENGINE_VERSION = "16"
_ALLOCATED_STORAGE_GB = 20

_TEMPLATE = """\
# Generated by PolicyGate AI for request {request_id}.
# Source plan hash: {plan_sha256}
# Do not hand-edit this file. Regenerate it from the approved evidence packet so
# the deployed configuration remains tied to the reviewed change.

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{region}"
}}

resource "aws_db_instance" "policygate_db" {{
  identifier = "policygate-{request_id_lower}"

  engine         = "postgres"
  engine_version = "{engine_version}"

  instance_class    = "{instance_class}"
  allocated_storage = {allocated_storage}
  storage_encrypted = {encryption_at_rest}

  multi_az                = {high_availability}
  backup_retention_period = {backup_retention_days}
  publicly_accessible     = {public_access}

  username                    = "policygate_admin"
  manage_master_user_password = true

  # Demo-safe teardown default. Production policy should normally require a
  # final snapshot and an explicit retention decision.
  skip_final_snapshot = true

  tags = {{
    ManagedBy   = "PolicyGateAI"
    RequestId   = "{request_id}"
    PlanSha256  = "{plan_sha256}"
    Environment = "{environment}"
  }}
}}

output "db_instance_endpoint" {{
  value = aws_db_instance.policygate_db.endpoint
}}

output "db_secret_arn" {{
  description = "Secrets Manager ARN created and managed by RDS for the master user."
  value       = try(aws_db_instance.policygate_db.master_user_secret[0].secret_arn, null)
}}
"""


def generate_terraform(evidence: dict) -> str:
    """Return HCL for an evidence packet created by ``build_evidence_packet``."""
    plan = evidence["proposed_plan"]
    request_id = evidence["request_id"]

    if plan.get("cloud") != "aws" or plan.get("database_engine") != "postgresql":
        raise ValueError(
            f"terraform_generator only supports aws/postgresql plans, got "
            f"cloud={plan.get('cloud')!r} database_engine={plan.get('database_engine')!r}"
        )

    return _TEMPLATE.format(
        request_id=request_id,
        request_id_lower=request_id.lower().replace("_", "-"),
        plan_sha256=evidence["plan_sha256"],
        region=plan["region"],
        instance_class=plan["instance_class"],
        engine_version=_ENGINE_VERSION,
        allocated_storage=_ALLOCATED_STORAGE_GB,
        encryption_at_rest=str(bool(plan["encryption_at_rest"])).lower(),
        high_availability=str(bool(plan["high_availability"])).lower(),
        backup_retention_days=int(plan["backup_retention_days"]),
        public_access=str(bool(plan["public_access"])).lower(),
        environment=plan["environment"],
    )


def write_terraform(evidence: dict, workdir: str | Path) -> Path:
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    tf_path = workdir / "main.tf"
    tf_path.write_text(generate_terraform(evidence), encoding="utf-8")
    return tf_path


def write_plan_manifest(
    evidence: dict,
    plan_file_sha256: str,
    plan_summary: str,
    workdir: str | Path,
) -> Path:
    """Write the exact plan-file hash and its human-readable summary."""
    manifest = {
        "request_id": evidence["request_id"],
        "config_plan_sha256": evidence["plan_sha256"],
        "terraform_plan_file_sha256": plan_file_sha256,
        "plan_summary": plan_summary.strip(),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    manifest_path = workdir / f"{evidence['request_id']}-terraform-plan-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    return manifest_path
